### ISSUE TITLE
AWS OIDC docs are missing the permissions block

### ISSUE THREAD

**Issue by joerg** [diggerhq/docs#4]
In this doc https://github.com/diggerhq/docs/blob/main/cloud-providers/authenticating-with-oidc-on-aws.md the permissions need to be placed in a `permissions` block according to https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions.

```
<snip>
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # required to merge PRs
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      statuses: write      # required to validate combined PR status
<snip>
```
